export const LOAD_PHOTOS_CURATED = "LOAD_PHOTOS_CURATED";
export const LOAD_PHOTOS_CURATED_SUCCESS = "LOAD_PHOTOS_CURATED_SUCCESS";
export const LOAD_PHOTOS_CURATED_FAILURE = "LOAD_PHOTOS_CURATED_FAILURE";
